### ISSUE TITLE
Create Parameter Grid

### ISSUE THREAD

**Issue by caseywescott** [cienicera/midi_fun#11]
Please implement this grid seen down in the middle of this page: 

https://cycling74.com/products/rnbo

<img width="1216" alt="Screen Shot 2024-11-23 at 1 18 51 PM" src="https://github.com/user-attachments/assets/4de31c7d-5d47-44c6-b968-bc2696005b3f">

It would be great to use the (x, y) values to define the parameter changes. 

I have tried to see how this was made and it is most likely made using p5.js library,

**Comment by Jemiiah** [comment]
@caseywescott I would love to work on this issue
