### ISSUE TITLE
Add Parameter Sliders to Web App

### ISSUE THREAD

**Issue by caseywescott** [cienicera/midi_fun#6]
* Add UI sliders for parameters like tempo, note duration, and transpose. These values will be sent to starknet to retrieve modified music.
* Ensure seamless integration with the KOJI library and Soundfont and/or RNBO synth.
Deliverables:
* Functional sliders with real-time effect on audio output and values to .
* Responsive design for various screen sizes.

**Comment by NueloSE** [comment]
May I take care of this?

**Comment by Jemiiah** [comment]
Hello I'm a frontend developer in web3 I have contributed in previous OD Hacks  i have made over 70+ contribution in past OD Hacks I intend in solving this issue with the following approach :

**Comment by CollinsC1O** [comment]
Would love to tackle this!

**Comment by josephchimebuka** [comment]
May I try my hand at this?

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by mimisavage** [comment]
Could I try solving this?

**Comment by Unickhub** [comment]
May I take this issue on?

**Comment by Benjtalkshow** [comment]
I'd like to handle this task. 
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

**Comment by ShantelPeters** [comment]
Is it okay if I tackle this?

**Comment by Supa-mega** [comment]
Is it okay if I take this?

**Comment by jancris100** [comment]
I'd like to take this issue.Would love to tackle this! I'm from dojo coding I have 2 years of experience as full stack developer and also Im actually work as mobile developer with figma

**Comment by Michaelkingsdev** [comment]
Can I be assigned to this?  I am an experienced frontend developer with 3 years of experience.

**Comment by morelucks** [comment]
Let me handle this issue!

**Comment by caseywescott** [comment]
Code has been merged!
